### ISSUE TITLE
Patient timelines using nonstandard codes in OMOP to MEDS conversion

### ISSUE THREAD

**Issue by akwasigroch** [Medical-Event-Data-Standard/meds_etl#32]
I am trying to convert an OMOP dataset into the MEDS standard. While the scripts run correctly, I am encountering an issue where the patients' timelines after conversion are recorded using only nonstandard codes.
I noticed that the function write_event_data() is reading source codes first, which should be converted to normalized concepts according to the comment in the code. However, the line `code = concept_id.replace(concept_id_map)` is transforming `concept_id` into `concept_code`, without referring to the standard codes.
How can I fix this problem?

**Comment by EthanSteinberg** [comment]
Hi @akwasigroch,

Sorry for the unclear documentation, but the design of writing non-standard codes is intentional here. The goal is to make the OMOP datasets as "similar as possible" to the non-OMOP datasets to make it easier to write generic labeling / featurization code.

You should still have access to the standard concepts by using Athena. And we try to save everything that is not in Athena to the metadata.json file. 

See https://github.com/som-shahlab/femr/blob/main/tutorials/1_Ontology.ipynb for an example of what that might look like for a MEDS client library.

I think it would be OK to store the standard codes in property, maybe "standard_code" if it seems to be causing issues though? Let me know if you think that would solve your problems. (I mainly just want to keep storing the non-standard properties in "code").

**Comment by akwasigroch** [comment]
My goal is to generate features for patient timelines using the script [GitHub tutorial](https://github.com/som-shahlab/femr/blob/main/tutorials/5_CLMBR%20Featurization%20And%20Modeling.ipynb).

I believe that hierarchical featurization is not necessary for my needs, and therefore, I do not require the ontology component. Could you please advise on the best way to restore the standard codes in this context? The ontology allows for the extraction of parent codes, but I need to determine which parent code to use.

**Comment by EthanSteinberg** [comment]
The best way is to modify the ETL to use a different set of concept ids (omop as opposed to source). https://github.com/Medical-Event-Data-Standard/meds_etl/blob/0.1.3/src/meds_etl/omop.py#L209 would be what needs to be modified.

(Also, make sure to update to 0.1.3 if you are on 0.1.2 as we just had to make a fix for 0.1.2).

**Comment by rvandewater** [comment]
@EthanSteinberg how about either making this a flag as there are multiple use cases (external validation, training new models from scratch being two that have different coding requirements) or providing functionality do scalable code conversion?

**Comment by EthanSteinberg** [comment]
@rvandewater  We already provide functionality for scalable code conversion with code_metadata.parquet.

I think it's only worth adding this flag is someone can explain why it's better than using code_metadata.parquet.

From my experience at Stanford, having multiple mutually incompatible versions of the same data causes tons of issues so I would prefer to avoid theses sorts of unnecessary incompatibilities whenever possible.

I'm going to close this issue unless someone brings up a limitation with code_metadata.parquet that makes this necessary.
